name: fastforge
description: A powerful and efficient tool for packaging and publishing your applications with ease.
version: 0.5.1
homepage: https://fastforge.dev
repository: https://github.com/fastforgedev/fastforge/tree/main/packages/fastforge
issue_tracker: https://github.com/fastforgedev/fastforge/issues

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  unified_distributor: ^0.1.1

dev_dependencies:
  dependency_validator: ^3.0.0
  mostly_reasonable_lints: ^0.1.2
  test: ^1.23.1

executables:
  fastforge: main
